### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by hmmbob**
I've overhauled the readme to make it easier to get to the correct information. Hope you'll find it helpful.

You can preview here; https://github.com/hmmbob/home-assistant-zonneplan-one/blob/patch-1/README.md

### CODE REVIEW

**Comment by hmmbob** [comment]
I was also thinking about dropping all ` | Energie` and `ONE` references, but not sure how you feel about that?

btw: it would only be the places visible in the docs and UI, we should keep `zonneplan_one` under the hood to prevent it becoming a breaking change.

**Comment by fsaris** [comment]
Tnx for the update. I'm okay with dropping One and Energy in readme and translations

**Comment by hmmbob** [comment]
Done 👍🏻 

I did verify that the change in the json is non-breaking: it nicely updates the name of the integration in your integration overview and everything else remains the same (entities, history, etc etc: no change at all). 

image

**Comment by fsaris** [comment]
Tnx for your addition

**Comment by hmmbob** [comment]
@fsaris Can you update this section? This is used by HACS as well :-)

image

**Comment by fsaris** [comment]
Done 👍🏻

**Pull request merged**
